server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sb-rest
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/a95973d1-dd8e-4baa-af11-d18f9863793b/v2.0
          jwk-set-uri: https://login.microsoftonline.com/a95973d1-dd8e-4baa-af11-d18f9863793b/discovery/v2.0/keys

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Azure AD Configuration
azure:
  activedirectory:
    tenant-id: a95973d1-dd8e-4baa-af11-d18f9863793b
    client-id: 87f707a0-3285-48a9-acb8-1c79ff06532a
    app-id-uri: ${AZURE_APP_ID_URI:api://87f707a0-3285-48a9-acb8-1c79ff06532a}

logging:
  level:
    com.example.sbrest: DEBUG
    org.springframework.security: DEBUG
